# Generated by Django 3.2.9 on 2021-11-26 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=1000, null=True, unique=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='Pub_files')),
                ('short_description', models.TextField(blank=True, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('bitBucket_link', models.URLField(blank=True, max_length=400, null=True)),
                ('docker_link', models.URLField(blank=True, max_length=400, null=True)),
                ('gitlab_link', models.URLField(blank=True, max_length=400, null=True)),
                ('github_link', models.URLField(blank=True, max_length=400, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.FileField(blank=True, null=True, upload_to='Pub_files')),
                ('color', models.CharField(choices=[('primary', 'primary'), ('warning', 'warning'), ('success', 'success'), ('danger', 'danger'), ('info', 'info')], max_length=25)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
            ],
            options={
                'verbose_name_plural': 'Topics',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='PublicationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pub_commenter', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commented_pub', to='blog.publication')),
            ],
            options={
                'verbose_name_plural': 'publication comments',
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication', to='blog.topics'),
        ),
    ]
