# Generated by Django 3.2.9 on 2021-11-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Pub_files'),
        ),
        migrations.AddField(
            model_name='publication',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
