# Generated by Django 3.2.9 on 2021-11-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_publication_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
