# Generated by Django 3.2.9 on 2021-11-07 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_publication_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.FileField(blank=True, null=True, upload_to='Pub_files')),
                ('colors', models.CharField(choices=[('primary', 'btn-primary-soft'), ('warning', ' btn-warning-soft'), ('success', ' btn-success-soft'), ('danger', ' btn-danger-soft'), ('info', ' btn-info-soft')], max_length=25)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
