# Generated by Django 3.2.9 on 2021-11-07 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic', to='blog.topics'),
        ),
    ]
