# Generated by Django 3.2.9 on 2021-11-07 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_publication_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topics',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Topics'},
        ),
        migrations.RenameField(
            model_name='topics',
            old_name='colors',
            new_name='color',
        ),
    ]
