# Generated by Django 3.2.9 on 2021-11-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_publication_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='bitBucket_link',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='docker_link',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='github_link',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='gitlab_link',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
