# Generated by Django 3.2.9 on 2021-11-10 13:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_publicationcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
