# Generated by Django 3.2.9 on 2021-11-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_topics_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=models.SlugField(max_length=1000, null=True, unique=True),
        ),
    ]
