# Generated by Django 3.2.9 on 2021-11-11 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_publication_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication', to='blog.topics'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='color',
            field=models.CharField(choices=[('primary', 'primary'), ('warning', 'warning'), ('success', 'success'), ('danger', 'danger'), ('info', 'info')], max_length=25),
        ),
    ]
