# Generated by Django 3.2.9 on 2021-12-10 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='profile_files')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(max_length=20, null=True)),
                ('profession', models.CharField(blank=True, max_length=200, null=True)),
                ('about', models.TextField(blank=True, max_length=300, null=True)),
                ('bio', models.TextField(blank=True, max_length=300, null=True)),
                ('facebook_link', models.URLField(blank=True, max_length=400, null=True)),
                ('linkedin_link', models.URLField(blank=True, max_length=400, null=True)),
                ('tweeter_link', models.URLField(blank=True, max_length=400, null=True)),
                ('github_link', models.URLField(blank=True, max_length=400, null=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profile',
            },
        ),
    ]
