# Generated by Django 3.2.9 on 2021-12-10 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_folloer_userprofile_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='follower',
            new_name='followers',
        ),
    ]
