# Generated by Django 3.2.9 on 2021-11-13 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_user_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='usename',
        ),
    ]
